### ISSUE TITLE
Retrieve more than 25 items?

### ISSUE THREAD

**Issue by k33k00** [browniebroke/deezer-python#31]
I've noticed that only 25 items are being pulled from the api at a time when doing search, getalbums etc..

**[Q]:** Is there a way to get either get them all at once, or is there some hidden pagination thing i'm missing?

for example, the code below will only return 25 items, even though there are more (artist dependent, I was using eminem as an example, artist search says he has 47)

```
def list_albums(artist):
    albums = artist.get_albums()
    for a in albums:
        data = a.asdict()
        yield {
            'id': data['id'],
            'title': data['title'],
            'link': data['link'],
            'artist': data['artist']['name'],
            'release_date': data['release_date'],
            'record_type': data['record_type'],
            'resource': a
            }
```

**Comment by browniebroke** [comment]
Looking at [the globals parameters](https://developers.deezer.com/api/parameters), this is achieved by adding `index` and `limit` to the URL parameters. This is surface in the search via arbitrary `kwargs`:

https://github.com/browniebroke/deezer-python/blob/066e49c52d258c881fbf67efed8d76a4a463126f/deezer/client.py#L243-L249

The other methods (like `get_albums`) don't support it, though, but that could be added easily.

I'd say in the spirit of making things explicit rather than implicit, we should probably specify `index` and `limit` as explicit optional keyword arguments for all the appropriate methods supporting them (basically the ones returning a list).

**Comment by browniebroke** [comment]
Also, pull requests to fix it are welcome!

**Comment by k33k00** [comment]
Awesome thanks. I'll have a pull request with you within the hour!

**Comment by browniebroke** [comment]
I think we can leave this open, and use [a keyword](https://help.github.com/articles/closing-issues-using-keywords/) to close it from the pull request.
