### ISSUE TITLE
How to obtain access token?

### ISSUE THREAD

**Issue by TheShubhendra** [browniebroke/deezer-python#414]
I am passing app_id and app_secrer to the client object, so it should request an access token automatically, but it doesn't

**Comment by browniebroke** [comment]
It doesn't, our documentation has [a section on authentication](https://deezer-python.readthedocs.io/en/stable/usage.html#authentication). Because this has to be authorized client side (the user has to enter their username & password to authorise your app), we cannot do it just with the app ID and app secret. Our API is a bit misleading, we should probably drop these parameters as they aren't really used. 

If you don't have a server yet to do the client side auth, you may obtain a token by running [the `oauth.py` script](https://github.com/browniebroke/deezer-python/blob/main/oauth.py). It's more a tool to develop on Deezer Python itself than for users of the library, but it might be useful to tinker in early stages. The documentation has [a section](https://deezer-python.readthedocs.io/en/stable/contributing.html#obtain-an-api-token) on how to use it.

Let me know how this goes, if anything is unclear, we can improve the docs.

**Comment by browniebroke** [comment]
I've released a CLI tool if you need to obtain a token to play with the API: https://pypi.org/project/deezer-oauth-cli/
